"""new todo table

Revision ID: ad438e6e3c03
Revises: 87f476b34ec6
Create Date: 2024-10-26 11:56:04.143883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad438e6e3c03'
down_revision: Union[str, None] = '87f476b34ec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_tag_association', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('todo_tag_association', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo_tag_association', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('todo_tag_association', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
